# Site settings
title: MENTGES TECNOLOGIA | Software Development - Offshore - Python, Ruby, Java, Javascript
email: bruno@mentgesinformatica.com.br
description: "Mentges Informática - Software development firm, offering offshore development in python, java, ruby and javascript."
baseurl: ""
url: "http://mentgesinformatica.com.br"

# Build settings
markdown: kramdown
permalink: pretty
